# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('desc', models.CharField(max_length=200, verbose_name='\u63cf\u8ff0')),
                ('thumb', models.URLField(verbose_name='\u7f29\u7565\u56fe')),
                ('full', models.URLField(verbose_name='\u539f\u59cb\u56fe')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
                'verbose_name': 'recall',
                'verbose_name_plural': 'recalls',
            },
        ),
    ]
