# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='recall',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4'),
        ),
    ]
