# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyme', '0002_auto_20170624_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('body', models.CharField(max_length=100, verbose_name='\u6b63\u6587')),
                ('body1', models.TextField(max_length=1000, verbose_name='\u6b63\u65871')),
                ('body2', models.CharField(max_length=200, verbose_name='\u6b63\u65872')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-updated'],
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
