# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyme', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.CharField(max_length=2000, verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body2',
            field=models.CharField(max_length=1000, verbose_name='\u6b63\u65872'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=500, verbose_name='\u6807\u9898'),
        ),
    ]
