# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-25 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyme', '0004_auto_20170625_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='\u6b63\u6587'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body2',
            field=models.TextField(max_length=1000, verbose_name='\u6b63\u65872'),
        ),
    ]
