# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-12 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyme', '0006_wordswall'),
    ]

    operations = [
        migrations.AddField(
            model_name='recall',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '\u7167\u7247'), (0, '\u89c6\u9891')], default=0, verbose_name='\u5206\u7c7b'),
        ),
    ]
